CREATE TABLE IF NOT EXISTS print_jobs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  saleId INT NOT NULL,
  estado ENUM('pending','printed','failed') NOT NULL DEFAULT 'pending',
  intentos TINYINT NOT NULL DEFAULT 0,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  printedAt DATETIME NULL,
  error VARCHAR(255) NULL,
  FOREIGN KEY (saleId) REFERENCES sales(id) ON DELETE CASCADE
) ENGINE=InnoDB;
